// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReminderApp.Migrations;

#nullable disable

namespace ReminderApp.Migrations
{
    [DbContext(typeof(ReminderDbContext))]
    [Migration("20230613180449_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ReminderApp.Models.Reminder", b =>
                {
                    b.Property<int>("R_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("R_Id"), 1L, 1);

                    b.Property<DateTime>("Add_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Finish")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("U_Id")
                        .HasColumnType("int");

                    b.Property<int?>("UserU_Id")
                        .HasColumnType("int");

                    b.HasKey("R_Id");

                    b.HasIndex("U_Id");

                    b.HasIndex("UserU_Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("ReminderApp.Models.User", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("U_Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("U_Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ReminderApp.Models.Reminder", b =>
                {
                    b.HasOne("ReminderApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("U_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReminderApp.Models.User", null)
                        .WithMany("CardOrders")
                        .HasForeignKey("UserU_Id");
                });

            modelBuilder.Entity("ReminderApp.Models.User", b =>
                {
                    b.Navigation("CardOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
