// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace sandy.Models;

public partial class Webuser
{
    public int UserID { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PWD { get; set; }

    public int Active { get; set; }

    public virtual ICollection<Todolist> Todolist { get; set; } = new List<Todolist>();
}