// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TodoAPI.Models
{
    public partial class Todolist
    {
        public int TodoId { get; set; }
        public int UserId { get; set; }
        public string Category { get; set; }
        public string Remark { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime? ModifyDate { get; set; }
        public DateTime? ScaheduledDate { get; set; }
        public bool? IsCompleted { get; set; } 

        public virtual Webuser User { get; set; }
    }
}